# Generated by Django 2.0.3 on 2018-03-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention', models.FloatField(verbose_name='Внимательность')),
                ('emotion', models.FloatField(verbose_name='Эмоциональная устойчивость')),
                ('generalchar', models.FloatField(verbose_name='Общие характеристики поведения')),
                ('charspeech', models.FloatField(verbose_name='Характеристика речи')),
                ('abstractmind', models.FloatField(verbose_name='Абстрактное мышление')),
                ('mind', models.FloatField(verbose_name='Память')),
                ('liability', models.FloatField(verbose_name='Ответственность')),
                ('speedmake', models.FloatField(verbose_name='Быстрота принятия решения')),
                ('physical', models.FloatField(verbose_name='Физическая выносливость')),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession.Profession', verbose_name='Профессии')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициенты'),
        ),
    ]
