# Generated by Django 2.0.3 on 2018-03-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='profession',
        ),
        migrations.AddField(
            model_name='profession',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Type', verbose_name='Тип'),
        ),
    ]
