# Generated by Django 2.0.3 on 2018-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0002_auto_20180327_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
    ]
