# Generated by Django 2.0.3 on 2018-04-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Ответ')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Answer', verbose_name='Ответ'),
        ),
    ]
