# Generated by Django 2.0.3 on 2018-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0004_auto_20180405_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отношение'),
        ),
    ]
