# Generated by Django 2.0.3 on 2018-04-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0005_auto_20180405_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Пятый-Ответ',
                'verbose_name_plural': 'Пятые-Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Четвертый-Ответ',
                'verbose_name_plural': 'Четвертые-Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Первый-Ответ',
                'verbose_name_plural': 'Первые-Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Третий-Ответ',
                'verbose_name_plural': 'Третьи-Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Второй-Ответ',
                'verbose_name_plural': 'Вторые-Ответы',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='answertwo',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='answerthree',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='answerone',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='answerfour',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='answerfive',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.Rate', verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerOne', verbose_name='Первый ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerTwo', verbose_name='Второй ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerThree', verbose_name='Третий ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerFour', verbose_name='Четвертый ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer5',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerFive', verbose_name='Пятый ответ'),
        ),
    ]
