# Generated by Django 2.0.3 on 2018-04-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0008_auto_20180406_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertypefour',
            options={'verbose_name': 'Четвертый-Ответ Типа', 'verbose_name_plural': 'Четвертые-Ответы Типа'},
        ),
        migrations.AlterModelOptions(
            name='answertypeone',
            options={'verbose_name': 'Первый-Ответ Типа', 'verbose_name_plural': 'Первые-Ответы Типа'},
        ),
        migrations.AlterModelOptions(
            name='answertypethree',
            options={'verbose_name': 'Третий-Ответ Типа', 'verbose_name_plural': 'Третьи-Ответы Типа'},
        ),
        migrations.AlterModelOptions(
            name='answertypetwo',
            options={'verbose_name': 'Второй-Ответ Типа', 'verbose_name_plural': 'Вторые-Ответы Типа'},
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='answer5',
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='answer1',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerTypeOne', verbose_name='Первый ответ Типа'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='answer2',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerTypeTwo', verbose_name='Второй ответ Типа'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='answer3',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerTypeThree', verbose_name='Третий ответ Типа'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='answer4',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.AnswerTypeFour', verbose_name='Четвертый ответ Типа'),
        ),
    ]
